---
engines:
  # General-purpose engines
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true

  # Frontend-related engines
  eslint:
    enabled: true
  stylelint:
    enabled: true

  # Backend-related engines
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  rubocop:
    enabled: true
  reek:
    enabled: true

ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.js"
  - "**.jsx"
  - "**.css"
  - "**.sass"
  - "**.vue"
exclude_paths:
- config/
- db/
- spec/
- vendor/bundle
- node_modules
