AllCops:
  Exclude:
    - '**/Rakefile'
    - '**/config.ru'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'

Metrics/LineLength:
  Enabled: false

Documentation:
  Enabled: false

Layout/IndentArray:
  EnforcedStyle: consistent

EmptyLinesAroundModuleBody:
  Enabled: false

EmptyLinesAroundClassBody:
  Enabled: false

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*'
