---
extends: stylelint-config-standard
processors:
  -
    - stylelint-processor-arbitrary-tags
    - fileFilterRegex:
      - \.erb$
      - \.handlebars$
      - \.hbs$
      - \.htm$
      - \.html$
      - \.mustache$
      - \.nunjucks$
      - \.php$
      - \.tag$
      - \.twig$
      - \.vue$
      - \.we$
      - \.xhtml$
      - \.xml$
