---
extends: stylelint-config-standard
rules:
  - indentation: 2
  - unit-whitelist:
    - em
    - rem
    - %
    - s
processors:
  -
    - stylelint-processor-arbitrary-tags
    - filterExtensions:
      - .erb
      - .handlebars
      - .hbs
      - .htm
      - .html
      - .mustache
      - .nunjucks
      - .php
      - .tag
      - .twig
      - .vue
      - .we
      - .xhtml
      - .xml
