---
extends: stylelint-config-primer
processors:
  -
    - stylelint-processor-arbitrary-tags
    - filterExtensions:
      - .erb
      - .handlebars
      - .hbs
      - .htm
      - .html
      - .mustache
      - .nunjucks
      - .php
      - .tag
      - .twig
      - .vue
      - .we
      - .xhtml
      - .xml
