# Database connection
#
default: &default
  encoding: utf8
  url: <%= ENV.fetch("DATABASE_URL_PREFIX", "") %>_unknown
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>

  # https://github.com/ankane/the-ultimate-guide-to-ruby-timeouts
  connect_timeout: <%= Integer(ENV.fetch("DB_CONNECT_TIMEOUT", 5)) %>
  checkout_timeout: <%= Integer(ENV.fetch("DB_CHECKOUT_TIMEOUT", 5)) %>
  read_timeout: <%= Integer(ENV.fetch("DB_READ_TIMEOUT", 5)) %>
  write_timeout: <%= Integer(ENV.fetch("DB_WRITE_TIMEOUT", 5)) %>

  # Statement timeouts
  #
  # variables:
  #   # For PostgreSQL
  #   statement_timeout: 250 # ms
  #   # For MySQL >= 5.7.8
  #   max_execution_time: 250 # ms

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL_PREFIX", "") %>_dev

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL_PREFIX", "") %>_test

ci:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL_PREFIX", "") %>_ci

staging:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL_PREFIX", "") %>_stg

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL_PREFIX", "") %>_prod
